'use client';

import { ReactNode, useEffect, useState, MouseEvent } from 'react';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useAuth } from '@/hooks/useAuth';
import api from '@/lib/api';
import CommandPalette from './CommandPalette';
import { useToast } from './ToastProvider';


type AppShellProps = {
  children: ReactNode;
  title?: string;
  subtitle?: string;
};

type ConversationListItem = {
  id: string;
  title: string | null;
  modelProfile: string;
  createdAt: string;
  updatedAt: string;
  pinned: boolean;
  archivedAt: string | null;
};

const navItems = [
  { href: '/', label: 'Dashboard' },
  { href: '/conversations', label: 'Conversations' },
  { href: '/settings', label: 'Settings' },
];

export default function AppShell({
  children,
  title,
  subtitle,
}: AppShellProps) {
  const pathname = usePathname();
  const router = useRouter();
  const { user, loading, logout } = useAuth();
  const { showToast } = useToast();

  const displayName = user?.name || user?.email || 'Guest';

  // Sidebar conversations state
  const [sidebarConversations, setSidebarConversations] = useState<
    ConversationListItem[]
  >([]);
  const [sidebarMenuOpenId, setSidebarMenuOpenId] = useState<string | null>(
    null,
  );

  // NEW: command palette open state
  const [commandOpen, setCommandOpen] = useState(false);

  const refreshSidebar = async () => {
    if (!user) return;
    try {
      const res = await api.get<ConversationListItem[]>('/conversations');
      setSidebarConversations(res.data);
    } catch (e) {
      console.error('Sidebar refresh failed:', e);
    }
  };

  // helper: sort conversations (pinned first, then newest)
  function sortSidebar(list: ConversationListItem[]) {
    return [...list].sort((a, b) => {
      if (a.pinned !== b.pinned) {
        return a.pinned ? -1 : 1; // pinned first
      }
      return new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime(); // newest first
    });
  }

  useEffect(() => {
    if (!user) return;

    refreshSidebar();

    const handler = () => refreshSidebar();
    window.addEventListener('conversation-updated', handler);

    return () => window.removeEventListener('conversation-updated', handler);
  }, [user]);

  // helper: let others know we changed conversations
  const broadcastUpdate = () => {
    if (typeof window !== 'undefined') {
      window.dispatchEvent(new CustomEvent('conversation-updated'));
    }
  };

  // NEW: global keyboard shortcut Cmd/Ctrl + K for command palette
  useEffect(() => {
    if (typeof window === 'undefined') return;

    const handler = (e: KeyboardEvent) => {
      const isMac = navigator.platform.toLowerCase().includes('mac');
      const meta = isMac ? e.metaKey : e.ctrlKey;

      if (meta && e.key.toLowerCase() === 'k') {
        e.preventDefault();
        setCommandOpen((prev) => !prev);
      }
    };

    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, []);

  const handleLogout = async () => {
    await logout();
    router.replace('/login');
  };

  const handleSidebarOpen = (id: string) => {
    router.push(`/conversations/${id}`);
  };

  const handleSidebarRename = async (convo: ConversationListItem) => {
    const currentTitle = convo.title || 'Untitled conversation';
    const newTitle = window.prompt('Rename conversation', currentTitle);
    if (!newTitle || newTitle.trim() === currentTitle.trim()) return;

    try {
      const res = await api.patch<ConversationListItem>(
        `/conversations/${convo.id}`,
        {
          title: newTitle,
          titleAutoGenerated: false,
        },
      );
      setSidebarConversations((prev) =>
        prev.map((c) => (c.id === convo.id ? { ...c, ...res.data } : c)),
      );
      setSidebarMenuOpenId(null);
      broadcastUpdate();
    } catch (err) {
      console.error('Failed to rename conversation (sidebar)', err);
      showToast({
        type: 'error',
        title: 'Rename failed',
        message: 'Could not rename conversation. Please try again.',
      });
    }
  };

  const handleSidebarDelete = async (convo: ConversationListItem) => {
    const ok = window.confirm(
      `Delete conversation "${convo.title || 'Untitled conversation'}"? This cannot be undone.`,
    );
    if (!ok) return;

    try {
      await api.delete(`/conversations/${convo.id}`);
      setSidebarConversations((prev) => prev.filter((c) => c.id !== convo.id));
      setSidebarMenuOpenId(null);
      broadcastUpdate();
    } catch (err) {
      console.error('Failed to delete conversation (sidebar)', err);
      showToast({
        type: 'error',
        title: 'Delete failed',
        message: 'Could not delete conversation. Please try again.',
      });
    }
  };

  const handleSidebarDuplicate = async (convo: ConversationListItem) => {
    try {
      const res = await api.post<ConversationListItem>(
        `/conversations/${convo.id}/duplicate`,
        {},
      );
      setSidebarConversations((prev) => [res.data, ...prev]);
      setSidebarMenuOpenId(null);
      broadcastUpdate();
    } catch (err) {
      console.error('Failed to duplicate conversation (sidebar)', err);
      showToast({
        type: 'error',
        title: 'Duplicate failed',
        message: 'Could not duplicate conversation. Please try again.',
      });
    }
  };

  // 3 dots: Pin / Unpin
  const handleSidebarTogglePin = async (
    id: string,
    currentPinned: boolean,
  ) => {
    try {
      const res = await api.patch<ConversationListItem>(
        `/conversations/${id}`,
        { pinned: !currentPinned },
      );

      setSidebarConversations((prev) =>
        sortSidebar(
          prev.map((c) => (c.id === id ? { ...c, ...res.data } : c)),
        ),
      );

      setSidebarMenuOpenId(null);
      broadcastUpdate();
    } catch (err) {
      console.error('Failed to toggle pin from sidebar', err);
    }
  };

  // 3 dots: Archive / Unarchive
  const handleSidebarArchiveToggle = async (
    id: string,
    isArchived: boolean,
  ) => {
    try {
      const payload = {
        archivedAt: isArchived ? null : new Date().toISOString(),
      };

      const res = await api.patch<ConversationListItem>(
        `/conversations/${id}`,
        payload,
      );

      setSidebarConversations((prev) => {
        if (isArchived) {
          // was archived -> now active
          // (if your /conversations endpoint only returns active, this case
          // will almost never happen from the sidebar, but we support it anyway)
          const exists = prev.some((c) => c.id === id);
          if (exists) {
            return sortSidebar(
              prev.map((c) => (c.id === id ? { ...c, ...res.data } : c)),
            );
          }
          return sortSidebar([res.data, ...prev]);
        } else {
          // active -> archived (remove from sidebar list)
          return prev.filter((c) => c.id !== id);
        }
      });

      setSidebarMenuOpenId(null);
      broadcastUpdate();
    } catch (err) {
      console.error('Failed to archive/unarchive from sidebar', err);
    }
  };


  const handleSidebarContextMenu = (
    e: MouseEvent<HTMLDivElement>,
    convoId: string,
  ) => {
    e.preventDefault();
    setSidebarMenuOpenId((prev) => (prev === convoId ? null : convoId));
  };

  // NEW: command palette → select conversation
  const handlePaletteSelectConversation = (id: string) => {
    handleSidebarOpen(id);
  };

  // NEW: command palette → create new chat
  const handlePaletteCreateNew = async () => {
    try {
      const res = await api.post<ConversationListItem>('/conversations', {
        modelProfile: 'gpt-4o',
      });

      setSidebarConversations((prev) => [res.data, ...prev]);
      broadcastUpdate();
      router.push(`/conversations/${res.data.id}`);
    } catch (err) {
      console.error('Failed to create conversation from palette', err);
      showToast({
        type: 'error',
        title: 'Could not create chat',
        message: 'Please try again.',
      });
    }
  };

  if (loading) {
    return (
      <main className="min-h-screen flex items-center justify-center bg-slate-50">
        <div className="rounded-xl bg-white/80 px-6 py-4 text-slate-700 shadow-sm border border-slate-200">
          Loading your workspace…
        </div>
      </main>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 flex">
      {/* Sidebar */}
      <aside className="hidden md:flex md:w-64 flex-col border-r border-slate-200 bg-slate-950 text-slate-100">
        <div className="px-5 pt-5 pb-4 border-b border-slate-800">
          <div className="text-lg font-semibold tracking-tight">
            Baqool<span className="text-emerald-400">AI</span>
          </div>
          <p className="mt-1 text-xs text-slate-400">
            Multi-model chat workspace
          </p>
        </div>

        <nav className="px-2 pt-4 pb-2 space-y-1 text-sm">
          {navItems.map((item) => {
            const active = pathname === item.href;
            return (
              <Link
                key={item.href}
                href={item.href}
                className={[
                  'flex items-center rounded-lg px-3 py-2 transition',
                  active
                    ? 'bg-slate-800 text-slate-50'
                    : 'text-slate-300 hover:bg-slate-900 hover:text-white',
                ].join(' ')}
              >
                {item.label}
              </Link>
            );
          })}
        </nav>

        {/* Workspace conversations list */}
        <div className="mt-2 flex-1 overflow-hidden flex flex-col">
          <div className="mx-2 mb-2 border-t border-slate-800" />
          <div className="px-3 pb-3 pt-1 text-[11px] font-semibold uppercase tracking-wide text-slate-500">
            Workspace
          </div>

          <div className="flex-1 px-2 pb-4 overflow-y-auto scroll-smooth space-y-2">
            {sidebarConversations.map((c) => (
              <div
                key={c.id}
                className="relative flex cursor-pointer items-center justify-between rounded-lg bg-slate-900 px-3 py-2 text-xs hover:bg-slate-800"
                onClick={() => handleSidebarOpen(c.id)}
                onContextMenu={(e) => handleSidebarContextMenu(e, c.id)}
              >
                <div className="flex flex-col">
                  <span className="font-medium truncate text-white">
                    {c.title || 'Untitled'}
                  </span>
                  <span className="text-[10px] text-slate-400">
                    {c.modelProfile}
                  </span>
                </div>

                <div className="relative">
                  <button
                    type="button"
                    className="rounded-full p-1 text-slate-400 hover:bg-slate-700 hover:text-white"
                    onClick={(e) => {
                      e.stopPropagation();
                      setSidebarMenuOpenId((prev) =>
                        prev === c.id ? null : c.id,
                      );
                    }}
                  >
                    ⋮
                  </button>

                  {sidebarMenuOpenId === c.id && (
                    <div className="absolute right-0 top-6 z-30 w-40 rounded-md border border-slate-700 bg-slate-900 py-1 text-[11px] text-slate-100 shadow-lg">
                      {/* Pin / Unpin */}
                      <button
                        className="flex w-full items-center justify-between px-3 py-1 hover:bg-slate-800"
                        onClick={(e) => {
                          e.stopPropagation();
                          handleSidebarTogglePin(c.id, c.pinned);
                        }}
                      >
                        <span>{c.pinned ? 'Unpin' : 'Pin'}</span>
                        <span className="text-[10px] text-slate-400">📌</span>
                      </button>

                      {/* Archive / Unarchive */}
                      <button
                        className="flex w-full items-center justify-between px-3 py-1 hover:bg-slate-800"
                        onClick={(e) => {
                          e.stopPropagation();
                          handleSidebarArchiveToggle(c.id, !!c.archivedAt);
                        }}
                      >
                        <span>{c.archivedAt ? 'Unarchive' : 'Archive'}</span>
                        <span className="text-[10px] text-slate-400">🗂</span>
                      </button>

                      <button
                        className="flex w-full items-center justify-between px-3 py-1 hover:bg-slate-800"
                        onClick={(e) => {
                          e.stopPropagation();
                          handleSidebarRename(c);
                        }}
                      >
                        <span>Rename</span>
                        <span className="text-[10px] text-slate-400">✏️</span>
                      </button>

                      <button
                        className="flex w-full items-center justify-between px-3 py-1 hover:bg-slate-800"
                        onClick={(e) => {
                          e.stopPropagation();
                          handleSidebarDuplicate(c);
                        }}
                      >
                        <span>Duplicate</span>
                        <span className="text-[10px] text-slate-400">⧉</span>
                      </button>

                      <button
                        className="flex w-full items-center justify-between px-3 py-1 text-red-400 hover:bg-red-900/30"
                        onClick={(e) => {
                          e.stopPropagation();
                          handleSidebarDelete(c);
                        }}
                      >
                        <span>Delete</span>
                        <span className="text-[10px] text-red-400">🗑</span>
                      </button>
                    </div>
                  )}

                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="border-t border-slate-800 px-4 py-4 text-xs text-slate-300">
          <div className="mb-1 font-semibold truncate">{displayName}</div>
          <button
            onClick={handleLogout}
            className="mt-1 inline-flex items-center rounded-full border border-slate-600 px-3 py-1 text-xs font-medium hover:bg-slate-800"
          >
            Logout
          </button>
        </div>
      </aside>

      {/* Main area */}
      <div className="flex-1 flex flex-col">
        <header className="sticky top-0 z-10 border-b border-slate-200 bg-white/90 backdrop-blur-sm">
          <div className="mx-auto max-w-6xl px-4 py-4 flex items-center justify-between gap-4">
            <div>
              <h1 className="text-xl font-semibold text-slate-900 tracking-tight">
                {title || 'Dashboard'}
              </h1>
              {subtitle && (
                <p className="mt-1 text-xs sm:text-sm text-slate-600">
                  {subtitle}
                </p>
              )}
            </div>

            <div className="flex items-center gap-3 text-xs sm:text-sm">
              <span className="hidden sm:inline text-slate-500">
                {displayName}
              </span>
              <button
                onClick={handleLogout}
                className="rounded-full bg-slate-900 px-3 py-1.5 text-xs font-medium text-white shadow-sm hover:bg-slate-800 active:bg-slate-900"
              >
                Logout
              </button>
            </div>
          </div>
        </header>

        <main className="flex-1">
          <div className="mx-auto max-w-6xl px-4 py-6 lg:py-8">{children}</div>
        </main>
      </div>

      {/* NEW: Command Palette overlay (Cmd/Ctrl + K) */}
      <CommandPalette
        open={commandOpen}
        onClose={() => setCommandOpen(false)}
        conversations={sidebarConversations}
        onSelectConversation={handlePaletteSelectConversation}
        onCreateNew={handlePaletteCreateNew}
      />
    </div>
  );
}
