// baqool-web/lib/api.ts
import axios from 'axios';

const api = axios.create({
  baseURL: 'http://localhost:4000', // NestJS backend
  timeout: 10000,
});

// Attach accessToken from localStorage to every request
api.interceptors.request.use((config) => {
  if (typeof window !== 'undefined') {
    const token = localStorage.getItem('accessToken');
    if (token) {
      config.headers = config.headers ?? {};
      config.headers.Authorization = `Bearer ${token}`;
    }
  }
  return config;
});

export default api;

/* ---------- Conversation helpers (Week 5) ---------- */

export interface UpdateConversationPayload {
  title?: string;
  modelProfile?: string;
  pinned?: boolean;
  archived?: boolean;
  titleAutoGenerated?: boolean;
}

export async function fetchConversations() {
  const res = await api.get('/conversations');
  return res.data;
}

export async function fetchConversation(id: string) {
  const res = await api.get(`/conversations/${id}`);
  return res.data;
}

export async function createConversation(payload: {
  title?: string;
  modelProfile?: string;
}) {
  const res = await api.post('/conversations', payload);
  return res.data;
}

export async function updateConversation(
  id: string,
  payload: UpdateConversationPayload,
) {
  const res = await api.patch(`/conversations/${id}`, payload);
  return res.data;
}

export async function duplicateConversation(id: string) {
  const res = await api.post(`/conversations/${id}/duplicate`);
  return res.data;
}

/**
 * Week 5: this is a SOFT DELETE (archive).
 */
export async function archiveConversation(id: string) {
  const res = await api.delete(`/conversations/${id}`);
  return res.data;
}

/* ---------- Messages helpers ---------- */

export async function listMessages(conversationId: string) {
  const res = await api.get(`/conversations/${conversationId}/messages`);
  return res.data;
}

export async function addMessage(
  conversationId: string,
  payload: {
    content: string;
    modelProfile?: string;
  },
) {
  const res = await api.post(
    `/conversations/${conversationId}/messages`,
    payload,
  );
  return res.data;
}

/* ---------- Preview helper (model routing preview) ---------- */

export async function previewMessage(payload: {
  content: string;
  lastModel?: string | null;
}) {
  const res = await api.post('/conversations/preview', payload);
  return res.data;
}
