// src/conversations/dto/update-conversation.dto.ts
import { isDate, IsBoolean, IsOptional, IsString, MaxLength, IsDate } from 'class-validator';
import { Type } from 'class-transformer';

export class UpdateConversationDto {
  @IsOptional()
  @IsString()
  @MaxLength(80)
  title?: string;

  @IsOptional()
  @IsString()
  modelProfile?: string; // e.g. "auto", "gpt-4o", "claude-3.5", "gemini-1.5-pro"

  @IsOptional()
  @IsBoolean()
  pinned?: boolean;

  /**
   * When true → archive (soft delete),
   * when false → unarchive.
   */
  @IsOptional()
  @Type(() => Date)
  @IsDate()
  archivedAt?: Date | null;

  /**
   * Whether the current title was auto-generated
   * (used by frontend to decide when to propose new titles).
   */
  @IsOptional()
  @IsBoolean()
  titleAutoGenerated?: boolean;
}


